import React from "react";
import { Feature } from "../../types";
import SearchIcon from "../icons/SearchIcon";
import SelectIcon from "../icons/SelectIcon";
import StandOutIcon from "../icons/StandOutIcon";
import "./features.css";

const Features = () => {
  const features: Feature[] = [
    {
      heading: "Search",
      body: "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
      icon: <SearchIcon height={72} width={72} />,
    },
    {
      heading: "Select",
      body: "Choose from thousands of options generated by the slogan maker that fit your needs.",
      icon: <SelectIcon height={72} width={72} />,
    },
    {
      heading: "Stand out",
      body: "Congrats on your new slogan. It's time to win the world!",
      icon: <StandOutIcon height={72} width={72} />,
    },
  ];
  return (
    <div className="feature__container">
      {features.map((feature, index) => (
        <div className="feature__item" key={index}>
          <div className="feature__icon--container">{feature.icon}</div>
          <h2>{feature.heading}</h2>
          <p>{feature.body}</p>
        </div>
      ))}
    </div>
  );
};

export default Features;
